# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
#zmodload zsh/zprof
#export XDG_CACHE_HOME=/nobackup/yishe2/p10k.cache
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

source $ZPLUG_HOME/init.zsh

# ----- plugin config start ------
#ZVM_VI_ESCAPE_BINDKEY=jk
VIM_MODE_VICMD_KEY=jk
MODE_CURSOR_VIINS="#00ff00 blinking bar"
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down
bindkey -M emacs '^P' history-substring-search-up
bindkey -M emacs '^N' history-substring-search-down
# ----- plugin config end ------
zplug "zsh-users/zsh-history-substring-search"
zplug romkatv/powerlevel10k, as:theme, depth:1
zplug "zsh-users/zsh-syntax-highlighting"
zplug "agkozak/zsh-z"
#zplug "zsh-users/zsh-syntax-highlighting", defer:2
#zplug "jeffreytse/zsh-vi-mode"
zplug "Aloxaf/fzf-tab"
zplug "softmoth/zsh-vim-mode"

# Install plugins if there are plugins that have not been installed
if ! zplug check --verbose; then
    echo; zplug install
fi

# Then, source plugins and add commands to $PATH
zplug load

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
alias rl="readlink -f"
function precommit {
        branch=$(git branch --show-current)
        active_regex="(CSC\w+).*"
        if [[ $branch =~ $active_regex ]]
        then
                /auto/firex/bin/precommit -d ${match[1]} $@
        else
                echo "Cannot find ddts from branch name ${branch}"
        fi
}

alias un_tgz="tar -xvzf"
alias un_gz="gzip -d"
alias fetch_repo="cd ${fea}; git fetch; cd-"
alias super_clean="lcleanup --killprocs;lcleanup --unmount;lcleanup --mqueues;lcleanup --reset"
#alias prep_vscode="/auto/smartdev/bin/compile-db -c ipv4/bgp lib infra sysdb sys platforms common linux inc manageability"
alias prep_vscode="/auto/smartdev/bin/compile-db -c ipv4/bgp sysdb manageability"
alias find_git_base="git merge-base origin/main HEAD"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

