name: test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 360
    steps:
      - name: Install zsh
        run: sudo apt-get update; sudo apt-get install zsh
        if: ${{ matrix.os == 'ubuntu-latest'}}
      - uses: actions/checkout@v3
      - name: Set up Python 3
        uses: actions/setup-python@v3
      - name: Cache Anaconda
        id: cache-py
        uses: actions/cache@v3
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ./env
          key: nokey
      - name: check home disk space
        run: |
          du -sh ~
      - name: Test
        run: |
          ./install.sh
        shell: zsh
      - name: check home disk space
        run: |
          du -sh ~

